# Generated by Django 4.2.2 on 2023-06-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Rock', 'Rock Music'), ('Pop', 'Pop Music'), ('Metal', 'Metal Music'), ('Jazz', 'Jazz Music'), ('R&B', 'R&B Music'), ('Country', 'Country Music'), ('Dance', 'Dance Music'), ('Hip Hop', 'Hip Hop Music'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
